name: ROCm CI Caller
on: 
  pull_request:  
    branches: [release/rocm-rel-6.4]  
    types: [opened, reopened, synchronize]  
  workflow_dispatch:  
  
jobs:  
  call-workflow:  
    uses: AMD-ROCm-Internal/rocm_ci_infra/.github/workflows/rocm_ci.yml@mainline 
    secrets: inherit  
    with:  
      input_sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}  
      input_pr_num: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || 0 }}  
      input_pr_url: ${{ github.event_name == 'pull_request' && github.event.pull_request.html_url || '' }}  
      input_pr_title: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || '' }}  
      repository_name: ${{ github.repository }}  
      base_ref: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref }}  
      trigger_event_type: ${{ github.event_name }}
